import React, { useState, useEffect } from 'react';
import api from '../api/client';
import Layout from '../components/Layout';

const Reports = ({ onNavigate }) => {
  const [lowStock, setLowStock] = useState([]);
  const [sortedProducts, setSortedProducts] = useState([]);
  const [sortConfig, setSortConfig] = useState({ by: 'name', order: 'asc' });
  const [loadingLowStock, setLoadingLowStock] = useState(true);
  const [loadingSorted, setLoadingSorted] = useState(true);
  const [activeTab, setActiveTab] = useState('analytics');
  const [generatingReport, setGeneratingReport] = useState(false);

  const fetchLowStock = async () => {
    setLoadingLowStock(true);
    try {
      const res = await api.get('/reports/low-stock');
      setLowStock(res.data.filter(p => p.quantity < 20));
    } catch (err) {
      console.error('Failed to fetch low stock report', err);
    }
    setLoadingLowStock(false);
  };
  
  const fetchSortedProducts = async () => {
    setLoadingSorted(true);
    try {
      const res = await api.get(`/reports/sorted-products?by=${sortConfig.by}&order=${sortConfig.order}`);
      setSortedProducts(res.data);
    } catch (err) {
      console.error('Failed to fetch sorted products', err);
    }
    setLoadingSorted(false);
  };

  useEffect(() => {
    fetchLowStock();
  }, []);
  
  useEffect(() => {
    fetchSortedProducts();
  }, [sortConfig]);

  const handleSortChange = (e) => {
    const { name, value } = e.target;
    setSortConfig(prev => ({...prev, [name]: value}));
  };

  const generatePDFReport = async () => {
    setGeneratingReport(true);
    try {
      // Simulate PDF generation - you can replace this with actual PDF generation logic
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Create a mock PDF download
      const reportData = {
        generatedAt: new Date().toLocaleString(),
        totalProducts: sortedProducts.length,
        lowStockItems: lowStock.length,
        inventoryValue: sortedProducts.reduce((sum, p) => sum + (p.price * p.quantity), 0),
        averageStock: sortedProducts.length > 0 ? Math.round(sortedProducts.reduce((sum, p) => sum + p.quantity, 0) / sortedProducts.length) : 0,
        stockDistribution: {
          high: sortedProducts.filter(p => p.quantity > 50).length,
          medium: sortedProducts.filter(p => p.quantity > 20 && p.quantity <= 50).length,
          low: sortedProducts.filter(p => p.quantity <= 20).length
        }
      };

      // Create a simple text file as mock PDF (replace with actual PDF generation)
      const content = `
InventoryPro Stock Report
Generated: ${reportData.generatedAt}

SUMMARY:
--------
Total Products: ${reportData.totalProducts}
Low Stock Items: ${reportData.lowStockItems}
Inventory Value: $${reportData.inventoryValue.toLocaleString()}
Average Stock Level: ${reportData.averageStock}

STOCK DISTRIBUTION:
-------------------
High Stock (>50): ${reportData.stockDistribution.high} items
Medium Stock (21-50): ${reportData.stockDistribution.medium} items
Low Stock (≤20): ${reportData.stockDistribution.low} items

LOW STOCK ALERT:
----------------
${lowStock.map(product => `- ${product.name} (SKU: ${product.sku}): ${product.quantity} units`).join('\n')}

This report was generated by InventoryPro Management System.
© ${new Date().getFullYear()} InventoryPro. All rights reserved.
      `;

      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `inventory-report-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      // Show success message
      alert('Report generated successfully! Check your downloads folder.');
      
    } catch (error) {
      console.error('Failed to generate report:', error);
      alert('Failed to generate report. Please try again.');
    } finally {
      setGeneratingReport(false);
    }
  };

  const StatCard = ({ title, value, subtitle, color = 'blue', icon }) => (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 hover:shadow-md transition-shadow duration-200">
      <div className="flex items-center">
        <div className={`flex-shrink-0 p-3 rounded-xl bg-gradient-to-br from-${color}-500 to-${color}-600`}>
          {icon}
        </div>
        <div className="ml-4 flex-1">
          <p className="text-sm font-medium text-gray-600">{title}</p>
          <p className="text-2xl font-bold text-gray-900 mt-1">{value}</p>
          {subtitle && <p className="text-sm text-gray-500 mt-1">{subtitle}</p>}
        </div>
      </div>
    </div>
  );

  return (
    <Layout onNavigate={onNavigate} title="Reports & Analytics">
      {/* Header Section */}
      <div className="mb-8">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-gray-600 mt-2">Real-time insights and inventory analytics for smart decision making</p>
          </div>
          {/* Generate Report Button */}
          <button
            onClick={generatePDFReport}
            disabled={generatingReport}
            className="group flex items-center justify-between p-4 bg-gradient-to-r from-blue-600 to-purple-600 rounded-xl shadow-md hover:shadow-lg transition-all duration-300 hover:scale-[1.02] disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <div className="flex items-center space-x-3">
              <div className="p-2 bg-white/20 rounded-lg">
                {generatingReport ? (
                  <svg className="w-5 h-5 text-white animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                  </svg>
                ) : (
                  <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                )}
              </div>
              <span className="font-semibold text-white">
                {generatingReport ? 'Generating Report...' : 'Generate Report'}
              </span>
            </div>
            {!generatingReport && (
              <svg className="w-4 h-4 text-white opacity-0 group-hover:opacity-100 transition-opacity duration-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              </svg>
            )}
          </button>
        </div>
      </div>

      {/* Stats Overview */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <StatCard 
          title="Total Products" 
          value={sortedProducts.length} 
          subtitle="In inventory"
          color="blue"
          icon={
            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
            </svg>
          }
        />
        <StatCard 
          title="Low Stock Items" 
          value={lowStock.length} 
          subtitle="Need restocking"
          color="red"
          icon={
            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.35 16.5c-.77.833.192 2.5 1.732 2.5z" />
            </svg>
          }
        />
        <StatCard 
          title="Inventory Value" 
          value={`$${sortedProducts.reduce((sum, p) => sum + (p.price * p.quantity), 0).toLocaleString()}`}
          subtitle="Total worth"
          color="green"
          icon={
            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1" />
            </svg>
          }
        />
        <StatCard 
          title="Avg. Stock Level" 
          value={sortedProducts.length > 0 ? Math.round(sortedProducts.reduce((sum, p) => sum + p.quantity, 0) / sortedProducts.length) : 0}
          subtitle="Per product"
          color="purple"
          icon={
            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
          }
        />
      </div>

      {/* Tab Navigation */}
      <div className="mb-6">
        <div className="border-b border-gray-200">
          <nav className="-mb-px flex space-x-8">
            {[
              { id: 'analytics', name: 'Analytics Overview' },
              { id: 'low-stock', name: 'Low Stock Alert' },
              { id: 'sorted', name: 'Product Catalog' }
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`py-3 px-1 border-b-2 font-medium text-sm transition-colors duration-200 ${
                  activeTab === tab.id
                    ? 'border-blue-500 text-blue-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
              >
                {tab.name}
              </button>
            ))}
          </nav>
        </div>
      </div>

      {/* Tab Content */}
      <div className="space-y-6">
        {activeTab === 'analytics' && (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h3 className="text-xl font-semibold text-gray-900 mb-4">Stock Distribution</h3>
            <div className="space-y-4">
              {[
                { level: 'High Stock', count: sortedProducts.filter(p => p.quantity > 50).length, color: 'bg-green-500', width: 'w-3/4' },
                { level: 'Medium Stock', count: sortedProducts.filter(p => p.quantity > 20 && p.quantity <= 50).length, color: 'bg-yellow-500', width: 'w-1/2' },
                { level: 'Low Stock', count: sortedProducts.filter(p => p.quantity <= 20).length, color: 'bg-red-500', width: 'w-1/4' }
              ].map((item, index) => (
                <div key={item.level} className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <div className={`w-3 h-3 rounded-full ${item.color}`}></div>
                    <span className="text-sm font-medium text-gray-700">{item.level}</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <div className="w-32 bg-gray-200 rounded-full h-2">
                      <div className={`h-2 rounded-full ${item.color} ${item.width} transition-all duration-500`}></div>
                    </div>
                    <span className="text-sm font-bold text-gray-900 w-8 text-right">{item.count}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === 'low-stock' && (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-xl font-semibold text-gray-900">Low Stock Alert</h3>
              <span className="px-3 py-1 bg-red-100 text-red-800 text-sm font-medium rounded-full">
                {lowStock.length} items need attention
              </span>
            </div>
            
            {loadingLowStock ? (
              <div className="flex justify-center items-center py-8">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-red-600"></div>
              </div>
            ) : (
              <div className="overflow-hidden">
                <table className="w-full">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Product</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">SKU</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Current Stock</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {lowStock.map(product => (
                      <tr key={product.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-medium text-gray-900">{product.name}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-500">{product.sku}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-semibold text-red-600">{product.quantity}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800">
                            Critical
                          </span>
                        </td>
                      </tr>
                    ))}
                    {lowStock.length === 0 && (
                      <tr>
                        <td colSpan="4" className="px-6 py-8 text-center text-gray-500">
                          <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                          </svg>
                          <p className="mt-2">All products are well stocked!</p>
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}

        {activeTab === 'sorted' && (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-xl font-semibold text-gray-900">Product Catalog</h3>
              <div className="flex space-x-3">
                <select 
                  name="by" 
                  value={sortConfig.by} 
                  onChange={handleSortChange}
                  className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                >
                  <option value="name">Sort by Name</option>
                  <option value="price">Sort by Price</option>
                  <option value="quantity">Sort by Quantity</option>
                </select>
                <select 
                  name="order" 
                  value={sortConfig.order} 
                  onChange={handleSortChange}
                  className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                >
                  <option value="asc">Ascending</option>
                  <option value="desc">Descending</option>
                </select>
              </div>
            </div>

            {loadingSorted ? (
              <div className="flex justify-center items-center py-8">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
              </div>
            ) : (
              <div className="overflow-hidden">
                <table className="w-full">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Product</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Category</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Price</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Stock</th>
                      <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {sortedProducts.map(product => (
                      <tr key={product.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-medium text-gray-900">{product.name}</div>
                          <div className="text-sm text-gray-500">{product.sku}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{product.category}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm font-semibold text-gray-900">${product.price.toFixed(2)}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-sm text-gray-900">{product.quantity}</div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                            product.quantity > 50 
                              ? 'bg-green-100 text-green-800'
                              : product.quantity > 20
                              ? 'bg-yellow-100 text-yellow-800'
                              : 'bg-red-100 text-red-800'
                          }`}>
                            {product.quantity > 50 ? 'In Stock' : product.quantity > 20 ? 'Low' : 'Critical'}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}
      </div>
    </Layout>
  );
};

export default Reports;